CREATE TABLE TIETOTIETORYHMA (
"RIVITUNNUS" NUMBER NOT NULL,
"TIETORYHMATUNNUS" NUMBER NOT NULL,
"TIETOTUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "PK_TIETOTIETORYHMA" PRIMARY KEY ("RIVITUNNUS"));
