CREATE TABLE JARJESTELMA_HENKILO_ROOLI_HIST (
"RIVITUNNUS" NUMBER NOT NULL,
"HENKILO_ID" NUMBER NOT NULL,
"ROOLI_ID" NUMBER NOT NULL,
"JARJESTELMA_ID" NUMBER NOT NULL,
"HISTORIATYYPPI" VARCHAR2(6) NOT NULL,
"RIVILUOTUPVM" TIMESTAMP (6),
"RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
CONSTRAINT "JARJESTELMA_HENKILO_ROOLI_HIST" PRIMARY KEY ("RIVITUNNUS"));

create sequence jarjhenkroolihist_seq start with 1;
create sequence jarjhenkroolihist_id_seq start with 1;