ALTER TABLE TIETOJARJESTELMASALKKU DROP COLUMN JARJ_OMISTAJA_ID;
ALTER TABLE TIETOJARJESTELMASALKKU DROP COLUMN JARJESTELMAVASTAAVA_LIVI_ID;
ALTER TABLE TIETOJARJESTELMASALKKU ALTER COLUMN TIETOTURVASOPIMUS SET DEFAULT 0;
UPDATE TIETOJARJESTELMASALKKU SET TIETOTURVASOPIMUS = 0 WHERE TIETOTURVASOPIMUS IS NULL;