ALTER TABLE HENKILO_TEMP MODIFY (TUNNUSTYYPPI VARCHAR2(255 CHAR));
ALTER TABLE HENKILO_TEMP MODIFY (KAYTTAJATUNNUS VARCHAR2(255 CHAR));
ALTER TABLE HENKILO_TEMP MODIFY (YRITYSTUNNUS VARCHAR2(255 CHAR));
ALTER TABLE HENKILO_TEMP MODIFY (MATKAPUHELIN VARCHAR2(255 CHAR));
