CREATE TABLE LOOGINENTIETOVARANTOFYYSINENTI (
"RIVITUNNUS" NUMBER NOT NULL,
"FYYSINENTIETOVARANTOTUNNUS" NUMBER NOT NULL,
"LOOGINENTIETOVARANTOTUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "LOOGINENTIETOVARANTOFYYSINE597" PRIMARY KEY ("RIVITUNNUS"));
