CREATE TABLE LOOGINENTIETOVARANTOTIETO (
"RIVITUNNUS" NUMBER NOT NULL,
"PAATIETORYHMATUNNUS" NUMBER NOT NULL,
"LOOGINENTIETOVARANTOTUNNUS" NUMBER NOT NULL,
"TIETORYHMATUNNUS" NUMBER NOT NULL,
"TIETOTUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "LOOGINENTIETOVARANTOTIETO_PK" PRIMARY KEY ("RIVITUNNUS"));
