CREATE TABLE PAATIETORYHMALAHDE (
"RIVITUNNUS" NUMBER NOT NULL,
"PAATIETORYHMATUNNUS" NUMBER NOT NULL,
"TIETOLAHDE" VARCHAR2(150) NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "PAATIETORYHMALAHDE_PK" PRIMARY KEY ("RIVITUNNUS"));
