CREATE TABLE PARAMETRIT (
"AVAIN" VARCHAR2(240),
"ARVO" VARCHAR2(240),
"RIVILUOTUPVM" TIMESTAMP (6),
"RIVIMUOKATTUPVM" TIMESTAMP (6),
"RIVIMUOKKAAJATUNNUS" VARCHAR2(240),
"KUVAUS" VARCHAR2(240),
"OTSIKKO" VARCHAR2(240),
CONSTRAINT "PK_PARAMETRIT" PRIMARY KEY ("AVAIN"));
