CREATE TABLE REKISTERIJULKAISU (
"JULKAISUTIETO_RIVIMUOKKAAJATUN" VARCHAR2(150) NOT NULL,
"RIVIMUOKKAAJATUNNUS" VARCHAR2(150) NOT NULL,
"RIVITUNNUS" NUMBER NOT NULL,
"SAHKOPOSTI" VARCHAR2(50),
"RIVITILA" VARCHAR2(15) NOT NULL,
"RIVILUOTUPVM" TIMESTAMP (6) NOT NULL,
"RIVIMUOKATTUPVM" TIMESTAMP (6) NOT NULL,
CONSTRAINT "REKISTERIJULKAISU_PK" PRIMARY KEY ("JULKAISUTIETO_RIVIMUOKKAAJATUN", "RIVIMUOKKAAJATUNNUS"));
