CREATE TABLE REKISTERIMUOKKAAJA (
"RIVIMUOKKAAJATUNNUS" VARCHAR2(150) NOT NULL,
"RIVITUNNUS" NUMBER NOT NULL,
"SAHKOPOSTI" VARCHAR2(50),
"RIVITILA" VARCHAR2(15) NOT NULL,
"RIVILUOTUPVM" TIMESTAMP (6) NOT NULL,
"RIVIMUOKATTUPVM" TIMESTAMP (6) NOT NULL,
"RIVIMUOKKAAJATUNNUS_1" VARCHAR2(150) NOT NULL,
CONSTRAINT "REKISTERIMUOKKAAJA_PK" PRIMARY KEY ("RIVIMUOKKAAJATUNNUS"));
