CREATE TABLE TIETOJARJESTELMASALKKUFYYSINEN (
"RIVITUNNUS" NUMBER NOT NULL,
"FYYSINENTIETOVARANTOTUNNUS" NUMBER NOT NULL,
"TIETOJARJESTELMATUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "TIETOJARJESTELMASALKKUFYYSI433" PRIMARY KEY ("RIVITUNNUS"));
