CREATE TABLE TIETOLAHDE (
"RIVITUNNUS" NUMBER NOT NULL,
"TIETOLAHDE" VARCHAR2(150) NOT NULL,
"PAATIETORYHMATUNNUS" NUMBER NOT NULL,
"TIETORYHMATUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
"TIETOTUNNUS" NUMBER NOT NULL,
CONSTRAINT "TIETOLAHDE_PK" PRIMARY KEY ("RIVITUNNUS"));
