-- FYYSINENTIETOVARANTO.sql
ALTER TABLE FYYSINENTIETOVARANTO ADD CONSTRAINT "REKISTERIKAYTTOTIHEYS_FYYSI848" FOREIGN KEY ("LINKKI") REFERENCES "REKISTERIKAYTTOTIHEYS" ("KAYTTOTIHEYS");
ALTER TABLE FYYSINENTIETOVARANTO ADD CONSTRAINT "REKISTERILINKKI_FYYSINENTIE80" FOREIGN KEY ("LINKKI") REFERENCES "REKISTERILINKKI" ("LINKKI");
ALTER TABLE FYYSINENTIETOVARANTO ADD CONSTRAINT "REKISTERIPALVELUTASO_FYYSIN192" FOREIGN KEY ("PALVELUTASO") REFERENCES "REKISTERIPALVELUTASO" ("PALVELUTASO");
ALTER TABLE FYYSINENTIETOVARANTO ADD CONSTRAINT "REKISTERITIETOKANTATEKNOLOG587" FOREIGN KEY ("TEKNOLOGIA") REFERENCES "REKISTERITIETOKANTATEKNOLOGIA" ("TEKNOLOGIA");

-- LOOGINENTIETOVARANTO.sql
ALTER TABLE LOOGINENTIETOVARANTO ADD CONSTRAINT "REKISTERIKASITEMALLI_LOOGIN894" FOREIGN KEY ("KASITEMALLI") REFERENCES "REKISTERIKASITEMALLI" ("KASITEMALLI");
ALTER TABLE LOOGINENTIETOVARANTO ADD CONSTRAINT "REKISTERILOOGINENTIETOVARAS624" FOREIGN KEY ("OMISTAJA") REFERENCES "REKISTERILOOGINENTIETOVARASTOO" ("OMISTAJA");
ALTER TABLE LOOGINENTIETOVARANTO ADD CONSTRAINT "REKISTERILOOGINENTIETOVARAS771" FOREIGN KEY ("KAYTTAJA") REFERENCES "REKISTERILOOGINENTIETOVARASTOS" ("KAYTTAJA");
ALTER TABLE LOOGINENTIETOVARANTO ADD CONSTRAINT "REKISTERIPAIVITYSTIHEYS_LOO465" FOREIGN KEY ("PAIVITYSTIHEYS") REFERENCES "REKISTERIPAIVITYSTIHEYS" ("PAIVITYSTIHEYS");
ALTER TABLE LOOGINENTIETOVARANTO ADD CONSTRAINT "REKISTERITIETORYHMAOMISTAJA760" FOREIGN KEY ("OMISTAJA") REFERENCES "REKISTERITIETORYHMAOMISTAJA" ("OMISTAJA");

-- LOOGINENTIETOVARANTOFYYSINENTI.sql
ALTER TABLE LOOGINENTIETOVARANTOFYYSINENTI ADD CONSTRAINT "FYYSINENTIETOVARANTO_LOOGIN571" FOREIGN KEY ("FYYSINENTIETOVARANTOTUNNUS") REFERENCES "FYYSINENTIETOVARANTO" ("FYYSINENTIETOVARANTOTUNNUS");
ALTER TABLE LOOGINENTIETOVARANTOFYYSINENTI ADD CONSTRAINT "LOOGINENTIETOVARANTO_LOOGIN813" FOREIGN KEY ("LOOGINENTIETOVARANTOTUNNUS") REFERENCES "LOOGINENTIETOVARANTO" ("LOOGINENTIETOVARANTOTUNNUS");

-- LOOGINENTIETOVARANTOTIETO.sql
ALTER TABLE LOOGINENTIETOVARANTOTIETO ADD CONSTRAINT "LOOGINENTIETOVARANTO_LOOGIN64" FOREIGN KEY ("LOOGINENTIETOVARANTOTUNNUS") REFERENCES "LOOGINENTIETOVARANTO" ("LOOGINENTIETOVARANTOTUNNUS");

-- LOOGINENTIETOVARANTOTOIMITUS.sql
ALTER TABLE LOOGINENTIETOVARANTOTOIMITUS ADD CONSTRAINT "LOOGINENTIETOVARANTO_LOOGIN245" FOREIGN KEY ("LOOGINENTIETOVARANTOTUNNUS") REFERENCES "LOOGINENTIETOVARANTO" ("LOOGINENTIETOVARANTOTUNNUS");
ALTER TABLE LOOGINENTIETOVARANTOTOIMITUS ADD CONSTRAINT "REKISTERITIEDONTOIMISTUSTAP746" FOREIGN KEY ("TOIMITUSTAPA") REFERENCES "REKISTERITIEDONTOIMISTUSTAPA" ("TOIMITUSTAPA");

-- PAATIETORYHMA.sql
ALTER TABLE PAATIETORYHMA ADD CONSTRAINT "REKISTERIJULKAISU_PAATIETOR403" FOREIGN KEY ("JULKAISUTIETO", "RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERIJULKAISU" ("JULKAISUTIETO_RIVIMUOKKAAJATUN", "RIVIMUOKKAAJATUNNUS");
ALTER TABLE PAATIETORYHMA ADD CONSTRAINT "REKISTERIMUOKKAAJA_PAATIETO685" FOREIGN KEY ("RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERIMUOKKAAJA" ("RIVIMUOKKAAJATUNNUS");
ALTER TABLE PAATIETORYHMA ADD CONSTRAINT "REKISTERITIETORYHMAOMISTAJA537" FOREIGN KEY ("OMISTAJA") REFERENCES "REKISTERITIETORYHMAOMISTAJA" ("OMISTAJA");
ALTER TABLE PAATIETORYHMA ADD CONSTRAINT "REKISTERITIETOSUOJATASO_PAA829" FOREIGN KEY ("TIETOSUOJATASO", "RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERITIETOSUOJATASO" ("TIETOSUOJATASO", "RIVIMUOKKAAJATUNNUS");
ALTER TABLE PAATIETORYHMA ADD CONSTRAINT "REKISTERITILA_PAATIETORYHMA_FK" FOREIGN KEY ("TILA", "RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERITILA" ("TILA", "RIVIMUOKKAAJATUNNUS");

-- PAATIETORYHMALAHDE.sql
ALTER TABLE PAATIETORYHMALAHDE ADD CONSTRAINT "PAATIETORYHMA_PAATIETORYHMA245" FOREIGN KEY ("PAATIETORYHMATUNNUS") REFERENCES "PAATIETORYHMA" ("PAATIETORYHMATUNNUS");
ALTER TABLE PAATIETORYHMALAHDE ADD CONSTRAINT "REKISTERITIETOLAHDE_PAATIET110" FOREIGN KEY ("TIETOLAHDE") REFERENCES "REKISTERITIETOLAHDE" ("TIETOLAHDE");

-- PAATIETORYHMASYNONYYMI.sql
ALTER TABLE PAATIETORYHMASYNONYYMI ADD CONSTRAINT "PAATIETORYHMA_PAATIETORYHMA110" FOREIGN KEY ("PAATIETORYHMATUNNUS") REFERENCES "PAATIETORYHMA" ("PAATIETORYHMATUNNUS");
ALTER TABLE PAATIETORYHMASYNONYYMI ADD CONSTRAINT "REKISTERISANASTO_PAATIETORY807" FOREIGN KEY ("SANA") REFERENCES "REKISTERISANASTO" ("SANA");

-- TIETO.sql
ALTER TABLE TIETO ADD CONSTRAINT "REKISTERITIETORYHMAOMISTAJA560" FOREIGN KEY ("OMISTAJA") REFERENCES "REKISTERITIETORYHMAOMISTAJA" ("OMISTAJA");
ALTER TABLE TIETO ADD CONSTRAINT "REKISTERITIETOSUOJATASO_TIE36" FOREIGN KEY ("TIETOSUOJATASO", "RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERITIETOSUOJATASO" ("TIETOSUOJATASO", "RIVIMUOKKAAJATUNNUS");
ALTER TABLE TIETO ADD CONSTRAINT "REKISTERITILA_TIETO_FK" FOREIGN KEY ("TILA", "RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERITILA" ("TILA", "RIVIMUOKKAAJATUNNUS");

-- TIETOJARJESTELMASALKKUFYYSINEN.sql
ALTER TABLE TIETOJARJESTELMASALKKUFYYSINEN ADD CONSTRAINT "FYYSINENTIETOVARANTO_FYYSIN398" FOREIGN KEY ("FYYSINENTIETOVARANTOTUNNUS") REFERENCES "FYYSINENTIETOVARANTO" ("FYYSINENTIETOVARANTOTUNNUS");

-- TIETOLAHDE.sql
ALTER TABLE TIETOLAHDE ADD CONSTRAINT "REKISTERITIETOLAHDE_TIETOLA559" FOREIGN KEY ("TIETOLAHDE") REFERENCES "REKISTERITIETOLAHDE" ("TIETOLAHDE");

-- TIETORYHMA.sql
ALTER TABLE TIETORYHMA ADD CONSTRAINT "REKISTERILOOGINENTIETOVARAS450" FOREIGN KEY ("KAYTTAJA") REFERENCES "REKISTERILOOGINENTIETOVARASTOS" ("KAYTTAJA");
ALTER TABLE TIETORYHMA ADD CONSTRAINT "REKISTERIMUOKKAAJA_TIETORYH135" FOREIGN KEY ("RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERIMUOKKAAJA" ("RIVIMUOKKAAJATUNNUS");
ALTER TABLE TIETORYHMA ADD CONSTRAINT "REKISTERITIETORYHMAOMISTAJA651" FOREIGN KEY ("OMISTAJA") REFERENCES "REKISTERITIETORYHMAOMISTAJA" ("OMISTAJA");
ALTER TABLE TIETORYHMA ADD CONSTRAINT "REKISTERITIETOSUOJATASO_TIE375" FOREIGN KEY ("TIETOSUOJATASO", "RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERITIETOSUOJATASO" ("TIETOSUOJATASO", "RIVIMUOKKAAJATUNNUS");
ALTER TABLE TIETORYHMA ADD CONSTRAINT "REKISTERITILA_TIETORYHMA_FK" FOREIGN KEY ("TILA", "RIVIMUOKKAAJATUNNUS") REFERENCES "REKISTERITILA" ("TILA", "RIVIMUOKKAAJATUNNUS");

-- TIETORYHMALAHDE.sql
ALTER TABLE TIETORYHMALAHDE ADD CONSTRAINT "REKISTERITIETOLAHDE_TIETORY46" FOREIGN KEY ("TIETOLAHDE") REFERENCES "REKISTERITIETOLAHDE" ("TIETOLAHDE");


-- TIETORYHMALOOGINENTIETOVARANTO.sql
ALTER TABLE TIETORYHMALOOGINENTIETOVARANTO ADD CONSTRAINT "LOOGINENTIETOVARANTO_TIETOR878" FOREIGN KEY ("LOOGINENTIETOVARANTOTUNNUS") REFERENCES "LOOGINENTIETOVARANTO" ("LOOGINENTIETOVARANTOTUNNUS");
