version: "3"
services:
    tomcat:
      container_name: tietokatalogi-backend
      image: tietokatalogi-backend:latest
      ports: 
        - 8080:8080
      environment:
        JAVA_OPTS: -Xmx2048m -Xms1024m -Dport.http=8080
        JDBC_URL: jdbc:postgresql://host.docker.internal:5432/tietokt?currentSchema=tietokt
        JDBC_USER: tietokt
        JDBC_PASSWORD: tietok123
        FIM_URL: https://testioag.liikennevirasto.fi/FIM/SimpleREST4FIM/1/
      networks: 
        - default
networks: 
  default:
    driver: bridge