version: "3"
services:
  tomcat:
    container_name: tietokatalogi-backend
    build:
      context: .
    ports:
      - 8082:8080
    environment:
      JAVA_OPTS: -Xmx2048m -Xms1024m -Dport.http=8080
      CATALINA_OPTS: "-Denv=local"
      AWS_ACCESS_KEY_ID: ""
      AWS_SECRET_ACCESS_KEY: ""
      AWS_SESSION_TOKEN: ""
      AWS_REGION: ""
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: tietokt
      POSTGRES_PASSWORD: tietok123

networks:
  default:
    driver: bridge
