CREATE ROLE TIETOKATALOGI_ROLE;
-- Object privileges granted to TIETOKATALOGI_ROLE
CREATE OR REPLACE DIRECTORY COMMON_DATA_PUMP_DIR AS '/opt/oracle/oradata/pump';
GRANT READ, WRITE ON DIRECTORY COMMON_DATA_PUMP_DIR TO TIETOKATALOGI_ROLE;
-- System privileges granted to TIETOKATALOGI_ROLE
GRANT CREATE PROCEDURE TO TIETOKATALOGI_ROLE;
GRANT CREATE SEQUENCE TO TIETOKATALOGI_ROLE;
GRANT CREATE SESSION TO TIETOKATALOGI_ROLE;
GRANT CREATE TABLE TO TIETOKATALOGI_ROLE;
GRANT CREATE TRIGGER TO TIETOKATALOGI_ROLE;
GRANT CREATE TYPE TO TIETOKATALOGI_ROLE;
GRANT CREATE VIEW TO TIETOKATALOGI_ROLE;
CREATE TABLESPACE TIETOKATALOGI_DATA DATAFILE 'tietokatalogi_data1.dbf' SIZE 20M REUSE AUTOEXTEND ON maxsize 5G;
create user tietok identified by livirules default tablespace TIETOKATALOGI_DATA quota 4G on TIETOKATALOGI_DATA;
GRANT TIETOKATALOGI_ROLE to tietok;

ALTER SYSTEM SET DEFERRED_SEGMENT_CREATION=FALSE;
