-- TIET-134: Lisaa jarjestelmalinkkaukset
CREATE TABLE JARJESTELMALINKKAUS (
"RIVITUNNUS" NUMBER NOT NULL,
"TIETOJARJESTELMATUNNUS" NUMBER NOT NULL,
"LINKATTAVA_ID" NUMBER NOT NULL,
"SUUNTA" VARCHAR(255),
"TYYPPI" VARCHAR(255),
"KUVAUS" VARCHAR(255),
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "PK_JARJESTELMALINKKAUS" PRIMARY KEY ("RIVITUNNUS"));

ALTER TABLE JARJESTELMALINKKAUS
  ADD CONSTRAINT check_suunta
CHECK ("SUUNTA" IN ('Sisään', 'Ulos'));

ALTER TABLE JARJESTELMALINKKAUS
  ADD CONSTRAINT check_tyyppi
CHECK ("TYYPPI" IN ('Sovellus', 'Järjestelmä'));
