-- Drop link table constraints or deleting looginen or fyysinen tietovaranto is not possible
ALTER TABLE LOOGINENTIETOVARANTOFYYSINENTI DROP CONSTRAINT FYYSINENTIETOVARANTO_LOOGIN571;
ALTER TABLE LOOGINENTIETOVARANTOFYYSINENTI DROP CONSTRAINT LOOGINENTIETOVARANTO_LOOGIN813;
