CREATE TABLE TIETOLOOGINENTIETOVARANTO (
"RIVITUNNUS" NUMBER NOT NULL,
"LOOGINENTIETOVARANTOTUNNUS" NUMBER NOT NULL,
"TIETOTUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "PK_TIETOLOOGINENTIETOVARANTO" PRIMARY KEY ("RIVITUNNUS"));
