CREATE TABLE TIETORYHMAPAATIETORYHMA (
"RIVITUNNUS" NUMBER NOT NULL,
"PAATIETORYHMATUNNUS" NUMBER NOT NULL,
"TIETORYHMATUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "PK_TIETORYHMAPAATIETORYHMA" PRIMARY KEY ("RIVITUNNUS"));
