CREATE TABLE JT_NAK_BKP (
"ID" NUMBER,
"SARAKKEEN_NIMI" VARCHAR2(255),
"RIVILUOTUPVM" DATE,
"RIVIMUOKATTUPVM" DATE,
"RIVIMUOKKAAJATUNNUS" VARCHAR2(255),
"DOCUMENT_ID" VARCHAR2(255),
"NIMI" VARCHAR2(255),
"JARJESTYS" NUMBER);
