-- TIET-145: FIM-henkilot

CREATE TABLE HENKILO (
  "TUNNUS" NUMBER NOT NULL,
  "OBJECT_ID" VARCHAR2(36 CHAR) NOT NULL,
  "NAYTTONIMI" VARCHAR2(255 CHAR),
  "TUNNUSTYYPPI" VARCHAR2(255 CHAR),
  "POISTUNUT" NUMBER(1),
  "KAYTTAJATUNNUS" VARCHAR2(255 CHAR),
  "YRITYS" VARCHAR2(255 CHAR),
  "YRITYSTUNNUS" VARCHAR2(255 CHAR),
  "ETUNIMI" VARCHAR2(255 CHAR),
  "SUKUNIMI" VARCHAR2(255 CHAR),
  "SAHKOPOSTI" VARCHAR2(255 CHAR),
  "MATKAPUHELIN" VARCHAR2(255 CHAR),
CONSTRAINT "HENKILO_PK" PRIMARY KEY ("TUNNUS"));

CREATE TABLE HENKILO_TEMP (
  "TUNNUS" NUMBER NOT NULL,
  "OBJECT_ID" VARCHAR2(36 CHAR) NOT NULL,
  "NAYTTONIMI" VARCHAR2(255 CHAR),
  "TUNNUSTYYPPI" VARCHAR2(36 CHAR),
  "POISTUNUT" NUMBER(1),
  "KAYTTAJATUNNUS" VARCHAR2(36 CHAR),
  "YRITYS" VARCHAR2(255 CHAR),
  "YRITYSTUNNUS" VARCHAR2(9 CHAR),
  "ETUNIMI" VARCHAR2(255 CHAR),
  "SUKUNIMI" VARCHAR2(255 CHAR),
  "SAHKOPOSTI" VARCHAR2(255 CHAR),
  "MATKAPUHELIN" VARCHAR2(13 CHAR),
CONSTRAINT "HENKILO_TEMP_PK" PRIMARY KEY ("TUNNUS"));

CREATE TABLE "ROOLI" (
  "TUNNUS" NUMBER NOT NULL,
  "NIMI" VARCHAR2(255) NOT NULL UNIQUE,
CONSTRAINT "ROOLI_PK" PRIMARY KEY ("TUNNUS"));

CREATE TABLE JARJESTELMA_HENKILO_ROOLI (
  "HENKILO_ID" NUMBER NOT NULL,
  "ROOLI_ID" NUMBER NOT NULL,
  "JARJESTELMA_ID" NUMBER NOT NULL,
  "RIVITUNNUS" NUMBER NOT NULL,
CONSTRAINT "JARJESTELMA_HENKILO_ROOLI_PK" PRIMARY KEY ("HENKILO_ID", "ROOLI_ID", "JARJESTELMA_ID"));

create sequence joinjarjhenkrooli_seq start with 1;
create sequence joinjarjhenkrooli_id_seq start with 1;

create sequence henkilo_seq start with 1;
create sequence henkilo_id_seq start with 1;
create sequence henkilo_temp_seq start with 1;
create sequence henkilo_temp_id_seq start with 1;

create sequence rooli_seq start with 1;
create sequence rooli_id_seq start with 1;

INSERT INTO ROOLI (TUNNUS, NIMI) VALUES (1, 'OMISTAJA');
INSERT INTO ROOLI (TUNNUS, NIMI) VALUES (2, 'VASTAAVA');
INSERT INTO ROOLI (TUNNUS, NIMI) VALUES (3, 'SIJAINEN');
