alter table TIETOJARJESTELMASALKKU add (JARJ_OMISTAJA_ID VARCHAR2(50));
alter table TIETOJARJESTELMASALKKU add (JARJESTELMAVASTAAVA_LIVI_ID VARCHAR2(50));
alter table TIETOJARJESTELMASALKKU add (TIETOTURVASOPIMUS NUMERIC(1,0));
