---
- hosts: all
  become: yes
  tasks:
    - name: Log deployment executor
      shell: echo "`date -u` {{ ansible_ssh_user }} {{versionhash}}" >> /var/lib/tomcat/deploymenthistory.txt

    - name: Copy script for fetching FIM
      template: src=../../src/main/resources/fetch_fim.template.sh dest={{ cron_job_fetch_fim }} mode=0755 owner=tomcat group=tomcat

    - name: Copy script for fetching sovha CSV
      template: src=../../src/main/resources/fetch_sovha.template.sh dest={{ cron_job_fetch_sovha }} mode=0755 owner=tomcat group=tomcat

    - name: Copy script for importing sovha CSV
      template: src=../../src/main/resources/import_sovha.template.sh dest={{ cron_job_import_sovha }} mode=0755 owner=tomcat group=tomcat

    - name: Create tietokatalogi application directory
      file: path=/var/lib/tomcat/webapps/tietokatalogi state=directory mode=0755 owner=tomcat group=tomcat

    - name: Unarchive local war to remote tomcat folder
      unarchive: src=../../target/TietokatalogiUI.war dest=/var/lib/tomcat/webapps/tietokatalogi mode=0755 owner=tomcat group=tomcat

    - name: Copy hibernate config
      template: src=../../src/main/resources/hibernate.cfg.template.xml dest=/var/lib/tomcat/webapps/tietokatalogi/WEB-INF/classes/hibernate.cfg.xml mode=0755 owner=tomcat group=tomcat

    - name: Copy fim config
      template: src=../../src/main/resources/config.template.properties dest=/var/lib/tomcat/webapps/tietokatalogi/WEB-INF/classes/config.properties mode=0755 owner=tomcat group=tomcat

    - name: Copy required jars to right places in server
      shell: "{{ item }}"
      with_items:
        - cp /usr/share/tomcat/lib/extras/tomcat-juli.jar /usr/share/tomcat/bin/tomcat-juli.jar
        - cp /usr/share/tomcat/lib/extras/tomcat-juli.jar /usr/share/tomcat/lib/tomcat-juli.jar
        - cp /usr/share/tomcat/lib/extras/tomcat-juli-adapters.jar /usr/share/tomcat/lib/tomcat-juli-adapters.jar

    - name: Delete tomcat global logging if excists
      file:
        state: absent
        path: /usr/share/tomcat/conf/logging.properties

    - name: Copy tomcat log4j config
      template: src=../templates/log4j_tomcat.properties dest=/usr/share/tomcat/lib/log4j.properties mode=0755 owner=tomcat group=tomcat

    - name: Copy log4j config
      template: src=../../src/main/resources/log4j.properties dest=/var/lib/tomcat/webapps/tietokatalogi/WEB-INF/classes/log4j.properties mode=0755 owner=tomcat group=tomcat

    - name: Restart tomcat
      service: name=tomcat state=restarted enabled=yes

    - name: Fetch FIM persons
      cron:
        name: "fim"
        minute: "00"
        hour: "1"
        job: "sh {{ cron_job_fetch_fim }};"

    - name: Fetch Sovha CSV
      cron:
        name: "fetch-csv"
        minute: "00"
        hour: "2"
        job: "expect {{ cron_job_fetch_sovha }};"

    - name: Import Sovha CSV
      cron:
        name: "import-csv"
        minute: "00"
        hour: "3"
        job: "sh {{ cron_job_import_sovha }};"
