---
- hosts: local
  become: no
  tasks:

    - name: Build required tietokatalogi WAR
      shell: ./build.sh
      args:
        chdir: ../../

    - name: Create hibernate config
      template: src=../../src/main/resources/hibernate.cfg.template.xml dest=../scripts/hibernate.cfg.xml

    - name: Create fim config
      template: src=../../src/main/resources/config.template.properties dest=../scripts/config.properties


    - name: Copy files to container
      shell: ./copy_to_tomcat_docker.sh
      args:
        chdir: ../scripts



