CREATE TABLE "SOVELLUS_TUONNIT" (
    "TUONTIAIKA" TIMESTAMP(6),
	"ONNISTUNUT" NUMBER,
	"TUONTI_ID" NUMBER NOT NULL
);

ALTER TABLE "SOVELLUS_TUONNIT" ADD CONSTRAINT "SOVELLUS_TUONNIT_PK" PRIMARY KEY ("TUONTI_ID");
ALTER TABLE "SOVELLUS_TUONNIT" ADD CONSTRAINT "SOVELLUS_TUONNIT_CHK1" CHECK (ONNISTUNUT IN (0, 1));
ALTER TABLE "SOVELLUS_TUONNIT" MODIFY ("ONNISTUNUT" NOT NULL ENABLE);
ALTER TABLE "SOVELLUS_TUONNIT" MODIFY ("TUONTIAIKA" NOT NULL ENABLE);
ALTER TABLE "SOVELLUS_TUONNIT" MODIFY ("TUONTI_ID" NOT NULL ENABLE);

CREATE SEQUENCE "SOVELLUS_TUONTI_ID_SEQ" START WITH 1;
