
CREATE TABLE "TIETOJARJPALVELUHISTORIA" (
    "RIVI_ID" NUMBER PRIMARY KEY,
    "HISTORIATYYPPI" VARCHAR2(6),
    "TUNNUS" NUMBER,
   	"NIMI" VARCHAR2(225) NOT NULL,
   	"KUVAUS" VARCHAR2(4000),
   	"KAYTTAJAROOLIT" VARCHAR2(225),
   	"TIETOJARJESTELMATUNNUS" NUMBER,
   	"ELINKAARI" VARCHAR2(20),
   	"RIVILUOTUPVM" TIMESTAMP (6),
    "RIVIMUOKATTUPVM" TIMESTAMP (6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150)
);

CREATE SEQUENCE "TIETOJARJPALVELUHIST_ID_SEQ" START WITH 1;