CREATE TABLE "TIETOJARJPALVELUTIETOHISTORIA" (
    "RIVITUNNUS" NUMBER PRIMARY KEY,
    "TIETOJARJESTELMAPALVELUTUNNUS" NUMBER NOT NULL,
    "TIETOLAJITUNNUS" NUMBER NOT NULL,
    "RIVITILA" VARCHAR2(6),
    "HISTORIATYYPPI" VARCHAR2(6),
    "RIVILUOTUPVM" TIMESTAMP(6),
    "RIVIMUOKATTUPVM" TIMESTAMP(6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150)
);

CREATE SEQUENCE "TIETOJARJPALVTIETOHIST_ID_SEQ" START WITH 1;
