-- TKYP-114

INSERT INTO "TIETOJARJESTELMA_KASITE_ARVO" (KASITE_WID, KASITE, ARVO) VALUES ('100', 'Budjetti', 'Järjestelmäbudjetti');
INSERT INTO "TIETOJARJESTELMA_KASITE_ARVO" (KASITE_WID, KASITE, ARVO) VALUES ('101', 'Budjetti', 'Yksikön oma');
INSERT INTO "TIETOJARJESTELMA_KASITE_ARVO" (KASITE_WID, KASITE, ARVO) VALUES ('102', 'Rahoitusmomentti', 'Toimintamenot');
INSERT INTO "TIETOJARJESTELMA_KASITE_ARVO" (KASITE_WID, KASITE, ARVO) VALUES ('103', 'Rahoitusmomentti', 'Radanpito');
INSERT INTO "TIETOJARJESTELMA_KASITE_ARVO" (KASITE_WID, KASITE, ARVO) VALUES ('104', 'Rahoitusmomentti', 'Tienpito');
INSERT INTO "TIETOJARJESTELMA_KASITE_ARVO" (KASITE_WID, KASITE, ARVO) VALUES ('105', 'Rahoitusmomentti', 'Vesiväylänpito');

ALTER TABLE "TIETOJARJESTELMASALKKU" ADD BUDJETTI VARCHAR2(255);
ALTER TABLE "TIETOJARJESTELMASALKKU" ADD RAHOITUSMOMENTTI VARCHAR2(255);

ALTER TABLE "TIETOJARJESTELMASALKKUHISTORIA" ADD BUDJETTI VARCHAR2(255);
ALTER TABLE "TIETOJARJESTELMASALKKUHISTORIA" ADD RAHOITUSMOMENTTI VARCHAR2(255);