-- TKYP-136 Järjestelmä-looginen -linkin backend-muutokset

CREATE TABLE "JARJESTELMALOOGINENHISTORIA" (
    "RIVI_ID" NUMBER PRIMARY KEY,
    "JARJESTELMATUNNUS" NUMBER NOT NULL,
    "LOOGINENTUNNUS" VARCHAR2(6),
    "RIVILUOTUPVM" TIMESTAMP (6),
    "HISTORIATYYPPI" VARCHAR2(6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150)
);

CREATE SEQUENCE "JARJESTELMALOOGINENHIST_ID_SEQ" START WITH 1;
