
-- INSERT INTO JARJESTELMALOOGINEN(LOOGINENTUNNUS, JARJESTELMATUNNUS) (
--     SELECT l.LOOGINENTIETOVARANTOTUNNUS, TO_NUMBER(l.KOODI)
--     FROM tietok.LOOGINENTIETOVARANTO l
--     WHERE l.KOODI IS NOT NULL
-- );
--
-- DROP TRIGGER JARJESTELMALOOGINEN_PK_INCR;


-- h2 does not allow dropping the column below without first removing these constraints
ALTER TABLE DEPR_LOOGINENTIETOVARANTOTIETO DROP CONSTRAINT LOOGINENTIETOVARANTO_LOOGIN64;
ALTER TABLE DEPR_LOOGINENTVTOIMITUS DROP CONSTRAINT LOOGINENTIETOVARANTO_LOOGIN245;
ALTER TABLE TIETORYHMALOOGINENTIETOVARANTO DROP CONSTRAINT LOOGINENTIETOVARANTO_TIETOR878;

ALTER TABLE LOOGINENTIETOVARANTO DROP COLUMN KOODI;
