
-- These table modifications break the view tietoomaisuus_jarjestelma_nimi, but the view is
-- fixed soon below. However, h2 does not allow breaking the view so we remove it first.
DROP VIEW TIETOOMAISUUS_JARJESTELMA_NIMI;
ALTER TABLE TIETOOMAISUUS ADD ALUSTOJEN_TYYP_JA_SIJ NUMBER;
ALTER TABLE TIETOOMAISUUS DROP COLUMN MODULAARISUUS;
ALTER TABLE TIETOOMAISUUS DROP COLUMN YLEISTYSTASOT;

ALTER TABLE TIETOOMAISUUSHISTORIA ADD ALUSTOJEN_TYYP_JA_SIJ NUMBER;
