-- TKYP-150 Lisää Tietovaranto-osio
CREATE TABLE "TIETOVARANTOHISTORIA" (
    "RIVI_ID" NUMBER PRIMARY KEY,
    "HISTORIATYYPPI" VARCHAR2(6),
    "TIETOVARANTOTUNNUS" NUMBER,
    "NIMI" VARCHAR2(225),
    "KUVAUS" VARCHAR2(4000),
    "VASTAAVA" VARCHAR2(225),
    "LISATIETO" VARCHAR2(4000),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
    "RIVILUOTUPVM" TIMESTAMP(6),
    "RIVIMUOKATTUPVM" TIMESTAMP(6)
);

CREATE SEQUENCE "TIETOVARANTOHIST_ID_SEQ" START WITH 1;
