-- TKYP-157 Päivityksiä Järjestelmäsalkun tietoturvakenttiin

-- NOTE: This script will not change history table data

-- TIETOTURVATASOLUOKITUS
-- Perus -> Jonkin verran tärkeä
-- Korotettu -> Tärkeä
-- Korkea -> Erittäin tärkeä
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (124, 'TIETOTURVATASOLUOKITUS', 'Jonkin verran tärkeä');
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (125, 'TIETOTURVATASOLUOKITUS', 'Tärkeä');
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (126, 'TIETOTURVATASOLUOKITUS', 'Erittäin tärkeä');
UPDATE TIETOJARJESTELMASALKKU SET TIETOTURVATASOLUOKITUS = 'Jonkin verran tärkeä' WHERE TIETOTURVATASOLUOKITUS = 'Perus';
UPDATE TIETOJARJESTELMASALKKU SET TIETOTURVATASOLUOKITUS = 'Tärkeä' WHERE TIETOTURVATASOLUOKITUS = 'Korotettu';
UPDATE TIETOJARJESTELMASALKKU SET TIETOTURVATASOLUOKITUS = 'Erittäin tärkeä' WHERE TIETOTURVATASOLUOKITUS = 'Korkea';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'TIETOTURVATASOLUOKITUS' AND ARVO = 'Perus';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'TIETOTURVATASOLUOKITUS' AND ARVO = 'Korotettu';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'TIETOTURVATASOLUOKITUS' AND ARVO = 'Korkea';

-- TIETOJEN_JULKISUUS
-- Julkinen -> Julkinen
-- ST1 (erittäin salainen) -> Turvallisuusluokiteltu
-- ST2 (salainen) -> Turvallisuusluokiteltu
-- ST3 (luottamuksellinen) -> Salassa pidettävä
-- ST4 (käyttörajoitettu) -> Harkinnanvaraisesti annettava
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (127, 'TIETOJEN_JULKISUUS', 'Turvallisuusluokiteltu');
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (128, 'TIETOJEN_JULKISUUS', 'Salassa pidettävä');
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (129, 'TIETOJEN_JULKISUUS', 'Harkinnanvaraisesti annettava');
UPDATE TIETOJARJESTELMASALKKU SET TIETOJEN_JULKISUUS = 'Turvallisuusluokiteltu' WHERE TIETOJEN_JULKISUUS = 'ST1 (erittäin salainen)';
UPDATE TIETOJARJESTELMASALKKU SET TIETOJEN_JULKISUUS = 'Turvallisuusluokiteltu' WHERE TIETOJEN_JULKISUUS = 'ST2 (salainen)';
UPDATE TIETOJARJESTELMASALKKU SET TIETOJEN_JULKISUUS = 'Salassa pidettävä' WHERE TIETOJEN_JULKISUUS = 'ST3 (luottamuksellinen)';
UPDATE TIETOJARJESTELMASALKKU SET TIETOJEN_JULKISUUS = 'Harkinnanvaraisesti annettava' WHERE TIETOJEN_JULKISUUS = 'ST4 (käyttörajoitettu)';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'TIETOJEN_JULKISUUS' AND ARVO = 'ST1 (erittäin salainen)';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'TIETOJEN_JULKISUUS' AND ARVO = 'ST2 (salainen)';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'TIETOJEN_JULKISUUS' AND ARVO = 'ST3 (luottamuksellinen)';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'TIETOJEN_JULKISUUS' AND ARVO = 'ST4 (käyttörajoitettu)';

-- JARJESTELMAN_TARKEYS_LIVILLE
-- Vähäinen -> Jonkin verran tärkeä
-- Jonkin verran tärkeä -> Jonkin verran tärkeä
-- Tärkeä -> Tärkeä
-- Elintärkeä -> Erittäin tärkeä
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (130, 'JARJESTELMAN_TARKEYS_LIVILLE', 'Erittäin tärkeä');
UPDATE TIETOJARJESTELMASALKKU SET JARJESTELMAN_TARKEYS_LIVILLE = 'Jonkin verran tärkeä' WHERE JARJESTELMAN_TARKEYS_LIVILLE = 'Vähäinen';
UPDATE TIETOJARJESTELMASALKKU SET JARJESTELMAN_TARKEYS_LIVILLE = 'Erittäin tärkeä' WHERE JARJESTELMAN_TARKEYS_LIVILLE = 'Elintärkeä';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'JARJESTELMAN_TARKEYS_LIVILLE' AND ARVO = 'Vähäinen';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'JARJESTELMAN_TARKEYS_LIVILLE' AND ARVO = 'Elintärkeä';

-- JARJ_TARKEYS_YHTEISTYOKUMP
-- Vähäinen -> ???
-- Jonkin verran tärkeä -> Jonkin verran tärkeä
-- Tärkeä -> Tärkeä
-- Elintärkeä -> Erittäin tärkeä
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (131, 'JARJ_TARKEYS_YHTEISTYOKUMP', 'Erittäin tärkeä');
UPDATE TIETOJARJESTELMASALKKU SET JARJ_TARKEYS_YHTEISTYOKUMP = 'Jonkin verran tärkeä' WHERE JARJ_TARKEYS_YHTEISTYOKUMP = 'Vähäinen';
UPDATE TIETOJARJESTELMASALKKU SET JARJ_TARKEYS_YHTEISTYOKUMP = 'Erittäin tärkeä' WHERE JARJ_TARKEYS_YHTEISTYOKUMP = 'Elintärkeä';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'JARJ_TARKEYS_YHTEISTYOKUMP' AND ARVO = 'Vähäinen';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'JARJ_TARKEYS_YHTEISTYOKUMP' AND ARVO = 'Elintärkeä';

-- JARJ_TARKEYS_YK
-- Vähäinen -> Vähäinen merkitys
-- Jonkin verran tärkeä -> Jonkin verran tärkeä
-- Tärkeä -> Tärkeä
-- Elintärkeä -> Erittäin tärkeä
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (132, 'JARJ_TARKEYS_YK', 'Vähäinen merkitys');
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (133, 'JARJ_TARKEYS_YK', 'Jonkin verran tärkeä');
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (134, 'JARJ_TARKEYS_YK', 'Tärkeä');
INSERT INTO TIETOJARJESTELMA_KASITE_ARVO (KASITE_WID, KASITE, ARVO) VALUES (135, 'JARJ_TARKEYS_YK', 'Erittäin tärkeä');
UPDATE TIETOJARJESTELMASALKKU SET JARJ_TARKEYS_YK = 'Vähäinen merkitys' WHERE JARJ_TARKEYS_YK = 'Vähäinen';
UPDATE TIETOJARJESTELMASALKKU SET JARJ_TARKEYS_YK = 'Erittäin tärkeä' WHERE JARJ_TARKEYS_YK = 'Elintärkeä';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'JARJ_TARKEYS_YK' AND ARVO = 'Vähäinen';
DELETE FROM TIETOJARJESTELMA_KASITE_ARVO WHERE KASITE = 'JARJ_TARKEYS_YK' AND ARVO = 'Elintärkeä';
