-- TKYP-160 Toimintaprosessit-sivulle automaattikuvaus
CREATE TABLE "TIETORYHMATIETOVARANTO" (
    "RIVITUNNUS" NUMBER,
    "TIETOVARANTOTUNNUS" NUMBER,
    "TIETORYHMATUNNUS" NUMBER,
    CONSTRAINT "TIETORYHMATIETOVARANTO_PK" PRIMARY KEY ("RIVITUNNUS")
);

CREATE SEQUENCE "TIETORYHMATIETOVARANTO_ID_SEQ" START WITH 1;
