-- TKYP-160 Toimintaprosessit-sivulle automaattikuvaus
CREATE TABLE "TIETORYHMATIETOVARANTOHISTORIA" (
    "RIVI_ID" NUMBER PRIMARY KEY,
    "TIETOVARANTOTUNNUS" NUMBER,
    "TIETORYHMATUNNUS" NUMBER,
    "RIVILUOTUPVM" TIMESTAMP (6),
    "HISTORIATYYPPI" VARCHAR2(6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150)
);

CREATE SEQUENCE "TIETORYHMATIETOVARAHIST_ID_SEQ" START WITH 1;
