-- TKYP-160 Toimintaprosessit-sivulle automaattikuvaus
INSERT INTO TIETORYHMATIETOVARANTO (RIVITUNNUS, TIETOVARANTOTUNNUS, TIETORYHMATUNNUS)
SELECT TIETORYHMATIETOVARANTO_ID_SEQ.nextval, TIETOVARANTOTUNNUS, TIETORYHMATUNNUS FROM TIETORYHMA WHERE TIETOVARANTOTUNNUS IS NOT NULL; 

INSERT INTO TIETORYHMATIETOVARANTOHISTORIA (RIVI_ID, TIETOVARANTOTUNNUS, TIETORYHMATUNNUS, RIVILUOTUPVM, HISTORIATYYPPI, RIVIMUOKKAAJATUNNUS)
SELECT TIETORYHMATIETOVARAHIST_ID_SEQ.nextval, TIETOVARANTOTUNNUS, TIETORYHMATUNNUS, SYSDATE, 'ADD', RIVIMUOKKAAJATUNNUS FROM TIETORYHMA WHERE TIETOVARANTOTUNNUS IS NOT NULL;
