-- TKYP-162: Tiedonhallintamalli
ALTER TABLE TIETOVARANTO ADD REKISTERINPITAJA VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD KASITTELYN_PERUSTE VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD KASITTELYN_TARKOITUS VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD VASTAANOTTAJARYHMAT VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD VIITTAUS_HENKTIETO_SOPIMUKSEEN VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD KOLMANNET_MAAT_JA_JARJESTOT VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD SUOJATOIMIA_DOKUMENTAATIO VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD YLLAPITO_MUUT_TAHOT VARCHAR2(255);
ALTER TABLE TIETOVARANTO ADD TEKNISET_ORG_TURVATOIMENPITEET VARCHAR2(255);

ALTER TABLE TIETOVARANTOHISTORIA ADD REKISTERINPITAJA VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD KASITTELYN_PERUSTE VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD KASITTELYN_TARKOITUS VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD VASTAANOTTAJARYHMAT VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD VIITTAUS_HENKTIETO_SOPIMUKSEEN VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD KOLMANNET_MAAT_JA_JARJESTOT VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD SUOJATOIMIA_DOKUMENTAATIO VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD YLLAPITO_MUUT_TAHOT VARCHAR2(255);
ALTER TABLE TIETOVARANTOHISTORIA ADD TEKNISET_ORG_TURVATOIMENPITEET VARCHAR2(255);
