-- ANALPK-1182: Tietokatalogi-muutokset
CREATE TABLE ORGANISAATIO (
    ORGANISAATIOTUNNUS NUMBER PRIMARY KEY,
    NIMI VARCHAR2(225),
    OSOITE VARCHAR2(255),
    SAHKOPOSTI VARCHAR2(255),
    PUHELINNUMERO VARCHAR2(255),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    RIVILUOTUPVM TIMESTAMP(6),
    RIVIMUOKATTUPVM TIMESTAMP(6)
);

CREATE SEQUENCE ORGANISAATIO_ID_SEQ START WITH 1;

CREATE TABLE ORGANISAATIOHISTORIA (
    RIVI_ID NUMBER PRIMARY KEY,
    HISTORIATYYPPI VARCHAR2(6),
    ORGANISAATIOTUNNUS NUMBER,
    NIMI VARCHAR2(225),
    OSOITE VARCHAR2(255),
    SAHKOPOSTI VARCHAR2(255),
    PUHELINNUMERO VARCHAR2(255),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    RIVILUOTUPVM TIMESTAMP(6),
    RIVIMUOKATTUPVM TIMESTAMP(6)
);

CREATE SEQUENCE ORGANISAATIOHISTORIA_ID_SEQ START WITH 1;

--Optionally remove any rows that are now invalid
--DELETE FROM TIETOVARANTOYHTEISREKISTPITAJA;
