-- ANALPK-1182: Tietokatalogi-muutokset
CREATE TABLE TIETOSUOJAVASTAAVA (
    TIETOSUOJAVASTAAVATUNNUS NUMBER PRIMARY KEY,
    NIMI VARCHAR2(225),
    OSOITE VARCHAR2(255),
    SAHKOPOSTI VARCHAR2(255),
    PUHELINNUMERO VARCHAR2(255),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    RIVILUOTUPVM TIMESTAMP(6),
    RIVIMUOKATTUPVM TIMESTAMP(6)
);

CREATE SEQUENCE TIETOSUOJAVASTAAVA_ID_SEQ START WITH 1;

CREATE TABLE TIETOSUOJAVASTAAVAHISTORIA (
    RIVI_ID NUMBER PRIMARY KEY,
    HISTORIATYYPPI VARCHAR2(6),
    TIETOSUOJAVASTAAVATUNNUS NUMBER,
    NIMI VARCHAR2(225),
    OSOITE VARCHAR2(255),
    SAHKOPOSTI VARCHAR2(255),
    PUHELINNUMERO VARCHAR2(255),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    RIVILUOTUPVM TIMESTAMP(6),
    RIVIMUOKATTUPVM TIMESTAMP(6)
);

CREATE SEQUENCE TIETOSUOJAVASTAAVAHIST_ID_SEQ START WITH 1;
