-- ANALPK-1171

CREATE TABLE TERMILOMAKE (
    "TERMILOMAKETUNNUS" NUMBER NOT NULL,
    "NIMI" VARCHAR2(255) NOT NULL,
    "ENSISIJ_TERMI" VARCHAR2(255),
    "SYNONYYMIT" VARCHAR2(255),
    "EI_SUOSIT_TERMI" VARCHAR2(255),
    "KAYTTOALUERAJAUS" VARCHAR2(255),
    "MAARITELMA" VARCHAR2(255),
    "KOMMENTIT" VARCHAR2(255),
    "VALMIS" VARCHAR2(255),
    "LAHDE" VARCHAR2(255),
    "OMISTAJA" VARCHAR2(255),
    "YDINKASITE" VARCHAR2(255),
    "HAKUTERMIT" VARCHAR2(255),
    "RIVILUOTUPVM" TIMESTAMP (6),
    "RIVIMUOKATTUPVM" TIMESTAMP (6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
    CONSTRAINT "PK_TERMILOMAKE" PRIMARY KEY ("TERMILOMAKETUNNUS"));

CREATE SEQUENCE TERMILOMAKE_ID_SEQ START WITH 1;
