CREATE TABLE LOOGINENTIETOVARANTOTOIMITUS (
"RIVITUNNUS" NUMBER NOT NULL,
"LOOGINENTIETOVARANTOTUNNUS" NUMBER NOT NULL,
"TOIMITUSTAPA" VARCHAR2(150) NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "LOOGINENTIETOVARANTOTOIMITU885" PRIMARY KEY ("RIVITUNNUS"));
