CREATE TABLE PAATIETORYHMASYNONYYMI (
"RIVITUNNUS" NUMBER NOT NULL,
"PAATIETORYHMATUNNUS" NUMBER NOT NULL,
"SANA" VARCHAR2(255) NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "PAATIETORYHMASYNONYYMI_PK" PRIMARY KEY ("RIVITUNNUS"));
