CREATE TABLE REKISTERITIETOLAHDE (
"TIETOLAHDE" VARCHAR2(150) NOT NULL,
"KUVAUS" VARCHAR2(4000),
"RIVITUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
"RIVILUOTUPVM" TIMESTAMP (6) NOT NULL,
"RIVIMUOKATTUPVM" TIMESTAMP (6) NOT NULL,
"RIVIMUOKKAAJATUNNUS" VARCHAR2(150) NOT NULL,
CONSTRAINT "REKISTERITIETOLAHDE_PK" PRIMARY KEY ("TIETOLAHDE"));
