CREATE TABLE TIETORYHMALAHDE (
"RIVITUNNUS" NUMBER NOT NULL,
"TIETOLAHDE" VARCHAR2(150) NOT NULL,
"PAATIETORYHMATUNNUS" NUMBER NOT NULL,
"TIETORYHMATUNNUS" NUMBER NOT NULL,
"RIVITILA" VARCHAR2(15) NOT NULL,
CONSTRAINT "TIETORYHMALAHDE_PK" PRIMARY KEY ("RIVITUNNUS"));
