CREATE TABLE TIETORYHMALOOGINENTIETOVARANTO (
"RIVITUNNUS" NUMBER NOT NULL,
"PAATIETORYHMATUNNUS" NUMBER,
"TIETORYHMATUNNUS" NUMBER,
"LOOGINENTIETOVARANTOTUNNUS" NUMBER,
"RIVITILA" VARCHAR2(15),
CONSTRAINT "TIETORYHMALOOGINENTIETOVARA643" PRIMARY KEY ("RIVITUNNUS"));
