CREATE TABLE TIETOVIRRAT (
"S_JARJESTELMA" NUMBER,
"T_JARJESTELMA" NUMBER,
"LUOTU" TIMESTAMP (6),
"MUOKATTU" TIMESTAMP (6),
"MUOKKAAJA" VARCHAR2(240),
"DOCUMENT_ID" VARCHAR2(255),
"LINKKI" VARCHAR2(255),
"TIETOSISALTO" VARCHAR2(4000),
"S_JARJESTELMA_NIMI" VARCHAR2(4000),
"T_JARJESTELMA_NIMI" VARCHAR2(4000),
"TIETOVIRTA_ID" VARCHAR2(240));
