ALTER TABLE JARJESTELMALINKKAUS
DROP CONSTRAINT CHECK_SUUNTA;

UPDATE JARJESTELMALINKKAUS SET SUUNTA = 'Luku' WHERE SUUNTA = 'Sisään';
UPDATE JARJESTELMALINKKAUS SET SUUNTA = 'Kirjoitus' WHERE SUUNTA = 'Ulos';

ALTER TABLE JARJESTELMALINKKAUS
ADD CONSTRAINT CHECK_SUUNTA CHECK
("SUUNTA" IN ('Luku', 'Kirjoitus'))
ENABLE;
