CREATE TABLE "TIETOK"."TIETOJARJESTELMAPALVELU"
   (	"TUNNUS" NUMBER,
	"NIMI" VARCHAR2(225 BYTE) NOT NULL,
	"KUVAUS" VARCHAR2(4000 BYTE),
	"KAYTTAJAROOLIT" VARCHAR2(225 BYTE),
	"TIETOJARJESTELMATUNNUS" NUMBER,
	"ELINKAARI" VARCHAR2(20 BYTE),
	"RIVILUOTUPVM" TIMESTAMP (6),
    "RIVIMUOKATTUPVM" TIMESTAMP (6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
	CONSTRAINT TIETOJARJESTELMAPALVELU_NEW_PK PRIMARY KEY ("TUNNUS"),
	CONSTRAINT TIETOJARJESTELMATUNNUS_FK1 FOREIGN KEY (TIETOJARJESTELMATUNNUS)
	    REFERENCES TIETOJARJESTELMASALKKU(TIETOJARJESTELMATUNNUS)
   );

CREATE SEQUENCE "TIETOJARJESTELMAPALVELU_ID_SEQ" START WITH 1;