
CREATE TABLE "TIETOK"."TIETOJARJPALVELUHISTORIA" (
    "RIVI_ID" NUMBER PRIMARY KEY,
    "HISTORIATYYPPI" VARCHAR2(6),
    "TUNNUS" NUMBER,
   	"NIMI" VARCHAR2(225 BYTE) NOT NULL,
   	"KUVAUS" VARCHAR2(4000 BYTE),
   	"KAYTTAJAROOLIT" VARCHAR2(225 BYTE),
   	"TIETOJARJESTELMATUNNUS" NUMBER,
   	"ELINKAARI" VARCHAR2(20 BYTE),
   	"RIVILUOTUPVM" TIMESTAMP (6),
    "RIVIMUOKATTUPVM" TIMESTAMP (6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150)
);

CREATE SEQUENCE "TIETOJARJPALVELUHIST_ID_SEQ" START WITH 1;