-- TKYP-124 Tieto-omaisuus -lomake
CREATE TABLE "TIETOK"."TIETOOMAISUUS" (
    "ID" NUMBER PRIMARY KEY,
    "TIETOJARJESTELMA_ID" NUMBER NOT NULL,
    "PRIMAARIKAYTTOTARVE" NUMBER,
    "SEKUNDAAR_KAYTTOTARPEET" NUMBER,
    "KAYTTAJAT" NUMBER,
    "MODULAARISUUS" NUMBER,
    "YLEISTYSTASOT" NUMBER,
    "MALLINNUSTAPA" NUMBER,
    "KAYTTOFORMAATIT" NUMBER,
    "HISTORIATIEDOT" NUMBER,
    "KATTAVUUS_JA_LAATU" NUMBER,
    "METATIEDOT" NUMBER,
    "MUUTOSTIEDOT" NUMBER,
    "SAATAVUUS" NUMBER,
    "HENKILOTIEDOT" NUMBER,
    "EHEYS" NUMBER,
    "AVOIMUUS" NUMBER,
    "IMMATERIAALIOIKEUDET" NUMBER,
    "YKSILOIVAT_TUNNISTEET" NUMBER,
    "PYSYVYYS" NUMBER,
    "DOKUMENTAATIO" NUMBER,
    "ELINKAARI" NUMBER,
    "RIVILUOTUPVM" TIMESTAMP (6),
    "RIVIMUOKATTUPVM" TIMESTAMP (6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
    "NIMI" VARCHAR2(225 BYTE),
    "KUVAUS" VARCHAR2(4000 BYTE)
);

CREATE SEQUENCE "TIETOOMAISUUS_ID_SEQ" START WITH 1;