
INSERT INTO JARJESTELMALOOGINEN(LOOGINENTUNNUS, JARJESTELMATUNNUS) (
    SELECT l.LOOGINENTIETOVARANTOTUNNUS, TO_NUMBER(l.KOODI)
    FROM tietok.LOOGINENTIETOVARANTO l
    WHERE l.KOODI IS NOT NULL
);

DROP TRIGGER JARJESTELMALOOGINEN_PK_INCR;

ALTER TABLE LOOGINENTIETOVARANTO DROP COLUMN KOODI;
