ALTER TABLE TIETOOMAISUUS ADD ALUSTOJEN_TYYP_JA_SIJ NUMBER;
ALTER TABLE TIETOOMAISUUS DROP COLUMN MODULAARISUUS;
ALTER TABLE TIETOOMAISUUS DROP COLUMN YLEISTYSTASOT;

ALTER TABLE TIETOOMAISUUSHISTORIA ADD ALUSTOJEN_TYYP_JA_SIJ NUMBER;
