-- TKYP-156 Lisää osio: Toimintaprosessit
CREATE TABLE "TOIMINTAPROSESSITIETOVARANTO" (
    "RIVITUNNUS" NUMBER,
    "TIETOVARANTOTUNNUS" NUMBER,
    "TOIMINTAPROSESSITUNNUS" NUMBER,
    CONSTRAINT "TOIMINTAPROSTIETOVARANTO_PK" PRIMARY KEY ("RIVITUNNUS")
);

CREATE SEQUENCE "TOIMINTAPROSTIETOVARANT_ID_SEQ" START WITH 1;
