-- TKYP-162: Tiedonhallintamalli
CREATE TABLE TIETOVARANTOYHTEISREKISTPITAJA (
    RIVITUNNUS NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    YHTEISREKISTERINPITAJA VARCHAR2(255),
    CONSTRAINT TIETOVARANTOYHTEISREKPITAJA_PK PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT TIETOVARANTOYHTEISREKPITAJA_FK FOREIGN KEY (TIETOVARANTOTUNNUS) REFERENCES TIETOVARANTO(TIETOVARANTOTUNNUS)
);

CREATE TABLE TIETOVARANTOREKISTEROITYRYHMA (
    RIVITUNNUS NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    REKISTEROITYRYHMA VARCHAR2(255),
    CONSTRAINT TIETOVARANTOREKISTRYHMA_PK PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT TIETOVARANTOREKISTRYHMA_FK FOREIGN KEY (TIETOVARANTOTUNNUS) REFERENCES TIETOVARANTO(TIETOVARANTOTUNNUS)
);

CREATE TABLE TIETOVARANTOHENKILOTIETORYHMA (
    RIVITUNNUS NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    HENKILOTIETORYHMA VARCHAR2(255),
    CONSTRAINT TIETOVARANTOHENKTIETORYHMA_PK PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT TIETOVARANTOHENKTIETORYHMA_FK FOREIGN KEY (TIETOVARANTOTUNNUS) REFERENCES TIETOVARANTO(TIETOVARANTOTUNNUS)
);

CREATE TABLE TIETOVARANTOTURVATOIMENPIDE (
    RIVITUNNUS NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    TURVATOIMENPIDE VARCHAR2(255),
    CONSTRAINT TIETOVARANTOTURVATOIMENPIDE_PK PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT TIETOVARANTOTURVATOIMENPIDE_FK FOREIGN KEY (TIETOVARANTOTUNNUS) REFERENCES TIETOVARANTO(TIETOVARANTOTUNNUS)
);

CREATE SEQUENCE TIETOVARYHTEISREKPITAJA_ID_SEQ START WITH 1;
CREATE SEQUENCE TIETOVARANTOREKISTRYHMA_ID_SEQ START WITH 1;
CREATE SEQUENCE TIETOVARAHENKTIETORYHMA_ID_SEQ START WITH 1;
CREATE SEQUENCE TIETOVARTURVATOIMENPIDE_ID_SEQ START WITH 1;

CREATE TABLE TIETOVARAYHTREKPITAJAHISTORIA (
    RIVI_ID NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    YHTEISREKISTERINPITAJA VARCHAR2(255),
    RIVILUOTUPVM TIMESTAMP (6),
    HISTORIATYYPPI VARCHAR2(6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150)
);

CREATE TABLE TIETOVARANTOREKISRYHMAHISTORIA (
    RIVI_ID NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    REKISTEROITYRYHMA VARCHAR2(255),
    RIVILUOTUPVM TIMESTAMP (6),
    HISTORIATYYPPI VARCHAR2(6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150)
);

CREATE TABLE TIETOVARHENKTIETORYHMAHISTORIA (
    RIVI_ID NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    HENKILOTIETORYHMA VARCHAR2(255),
    RIVILUOTUPVM TIMESTAMP (6),
    HISTORIATYYPPI VARCHAR2(6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150)
);

CREATE TABLE TIETOVARATURVATOIMPIDEHISTORIA (
    RIVI_ID NUMBER,
    TIETOVARANTOTUNNUS NUMBER,
    TURVATOIMENPIDE VARCHAR2(255),
    RIVILUOTUPVM TIMESTAMP (6),
    HISTORIATYYPPI VARCHAR2(6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150)
);

CREATE SEQUENCE TIETOVARAYHTREKPITAHIST_ID_SEQ START WITH 1;
CREATE SEQUENCE TIETOVARANTREKRYHMAHIST_ID_SEQ START WITH 1;
CREATE SEQUENCE TIETOVARHENTIETRYHMHIST_ID_SEQ START WITH 1;
CREATE SEQUENCE TIETOVARTURVTOIMPIDHIST_ID_SEQ START WITH 1;
