-- ANALPK-1171

CREATE TABLE TERMILOMAKEHISTORIA (
    "RIVI_ID" NUMBER NOT NULL,
    "TERMILOMAKETUNNUS" NUMBER NOT NULL,
    "NIMI" VARCHAR2(255) NOT NULL,
    "ENSISIJ_TERMI" VARCHAR2(255),
    "SYNONYYMIT" VARCHAR2(255),
    "EI_SUOSIT_TERMI" VARCHAR2(255),
    "KAYTTOALUERAJAUS" VARCHAR2(255),
    "MAARITELMA" VARCHAR2(255),
    "HUOMAUTUS_1" VARCHAR2(255),
    "HUOMAUTUS_2" VARCHAR2(255),
    "KOMMENTIT" VARCHAR2(255),
    "VALMIS" VARCHAR2(255),
    "LAHDE" VARCHAR2(255),
    "OMISTAJA" VARCHAR2(255),
    "YDINKASITE" VARCHAR2(255),
    "HAKUTERMIT" VARCHAR2(255),
    "HISTORIATYYPPI" VARCHAR2(6),
    "RIVILUOTUPVM" TIMESTAMP (6),
    "RIVIMUOKATTUPVM" TIMESTAMP (6),
    "RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
    CONSTRAINT "PK_TERMILOMAKEHISTORIA" PRIMARY KEY ("RIVI_ID"));

CREATE SEQUENCE TERMILOMAKEHIST_ID_SEQ START WITH 1;
