CREATE TABLE TERMILOMAKEHIERARKKASITE (
    RIVITUNNUS NUMBER,
    HIERARKKINEN_YLAKASITE NUMBER,
    HIERARKKINEN_ALAKASITE NUMBER,
    RIVITILA VARCHAR2(6),
    CONSTRAINT TERMILOMAKEHIERARKKASITE_PK PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT HIERARKKINEN_YLAKASITE_FK FOREIGN KEY (HIERARKKINEN_YLAKASITE) REFERENCES TERMILOMAKE(TERMILOMAKETUNNUS),
    CONSTRAINT HIERARKKINEN_ALAKASITE_FK FOREIGN KEY (HIERARKKINEN_ALAKASITE) REFERENCES TERMILOMAKE(TERMILOMAKETUNNUS)
);
CREATE SEQUENCE TERMILOMAKEHIERKASITE_ID_SEQ START WITH 1;

CREATE TABLE TERMILOMAKEHKASITEHISTORIA (
    RIVI_ID NUMBER,
    HIERARKKINEN_ALAKASITE NUMBER,
    HIERARKKINEN_YLAKASITE NUMBER,
    HISTORIATYYPPI VARCHAR2(6),
    RIVILUOTUPVM TIMESTAMP (6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    CONSTRAINT TERMILOMAKEHKASITEHISTORIA_PK PRIMARY KEY (RIVI_ID)
);

CREATE SEQUENCE TERMILOMAKEHIERKHIST_ID_SEQ START WITH 1;

--- TERMILOMAKE KOOSTUMUSSUHTEINEN KASITE
CREATE TABLE TERMILOMAKEKOOSTKASITE (
    RIVITUNNUS NUMBER,
    KOOSTUMUSSUHTEINEN_YLAKASITE NUMBER,
    KOOSTUMUSSUHTEINEN_ALAKASITE NUMBER,
    RIVITILA VARCHAR2(6),
    CONSTRAINT TERMILOMAKEKOOSTKASITE_PK PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT KOOSTUMUSSUHT_YLAKASITE_FK FOREIGN KEY (KOOSTUMUSSUHTEINEN_YLAKASITE) REFERENCES TERMILOMAKE(TERMILOMAKETUNNUS),
    CONSTRAINT KOOSTUMUSSUHT_ALAKASITE_FK FOREIGN KEY (KOOSTUMUSSUHTEINEN_ALAKASITE) REFERENCES TERMILOMAKE(TERMILOMAKETUNNUS)
);
CREATE SEQUENCE TERMILOMAKEKOOSTKASITE_ID_SEQ START WITH 1;

CREATE TABLE TERMILOMAKEKOOSTKASIHISTORIA (
    RIVI_ID NUMBER,
    KOOSTUMUSSUHTEINEN_YLAKASITE NUMBER,
    KOOSTUMUSSUHTEINEN_ALAKASITE NUMBER,
    HISTORIATYYPPI VARCHAR2(6),
    RIVILUOTUPVM TIMESTAMP (6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    CONSTRAINT TERMILOMAKEKOOSTKASHISTORIA_PK PRIMARY KEY (RIVI_ID)
);

CREATE SEQUENCE TERMILOMAKEKOOSTKASHIST_ID_SEQ START WITH 1;

--- TERMILOMAK ASSOSIATIIVINEN KASITE
CREATE TABLE TERMILOMAKEASSOSKASITE (
    RIVITUNNUS NUMBER,
    ASSOSIATIIVINEN_YLAKASITE NUMBER,
    ASSOSIATIIVINEN_ALAKASITE NUMBER,
    RIVITILA VARCHAR2(6),
    CONSTRAINT TERMILOMAKEASSOSKASITE_PK PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT ASSOSIATIIVINEN_YLAKASITE_FK FOREIGN KEY (ASSOSIATIIVINEN_YLAKASITE) REFERENCES TERMILOMAKE(TERMILOMAKETUNNUS),
    CONSTRAINT ASSOSIATIIVINEN_ALAKASITE_FK FOREIGN KEY (ASSOSIATIIVINEN_ALAKASITE) REFERENCES TERMILOMAKE(TERMILOMAKETUNNUS)
);
CREATE SEQUENCE TERMILOMAKEASSOSKASITE_ID_SEQ START WITH 1;

CREATE TABLE TERMILOMAKEASKASIHISTORIA (
    RIVI_ID NUMBER,
    ASSOSIATIIVINEN_YLAKASITE NUMBER,
    ASSOSIATIIVINEN_ALAKASITE NUMBER,
    HISTORIATYYPPI VARCHAR2(6),
    RIVILUOTUPVM TIMESTAMP (6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    CONSTRAINT TERMILOMAKEASKASIHISTORIA_PK PRIMARY KEY (RIVI_ID)
);

CREATE SEQUENCE TERMILOMAKEASKAHISTORIA_ID_SEQ START WITH 1;
