-- ANALPK-1323 HUOMAUTUS

CREATE TABLE JOINHUOMAUTUS (
    RIVITUNNUS NUMBER,
    TERMILOMAKETUNNUS NUMBER,
    HUOMAUTUS VARCHAR2(4000),
    RIVITILA VARCHAR2(6),
    CONSTRAINT PK_JOINHUOMAUTUS PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT FK_TERMILOMAKE FOREIGN KEY (TERMILOMAKETUNNUS) REFERENCES TERMILOMAKE(TERMILOMAKETUNNUS)
);
CREATE SEQUENCE JOINHUOMAUTUS_ID_SEQ START WITH 1;

CREATE TABLE JOINHUOMAUTUSHISTORIA (
    RIVI_ID NUMBER,
    TERMILOMAKETUNNUS NUMBER,
    HUOMAUTUS VARCHAR2(4000),
    HISTORIATYYPPI VARCHAR2(6),
    RIVILUOTUPVM TIMESTAMP (6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150),
    CONSTRAINT PK_JOINHUOMAUTUSHISTORIA PRIMARY KEY (RIVI_ID)
);
CREATE SEQUENCE JOINHUOMAUTUSHIST_ID_SEQ START WITH 1;
