-- ANALPK-1391
CREATE TABLE TIETOJARJPALVLIITTYVAJARJ (
    RIVITUNNUS NUMBER NOT NULL,
    TIETOJARJPALVELUTUNNUS NUMBER,
    LIITTYVAJARJESTELMATUNNUS NUMBER,
    CONSTRAINT PK_TIETOJARJPALVLIITTYVAJARJ PRIMARY KEY (RIVITUNNUS),
    CONSTRAINT FK_TIETOJARJPALVLIITTYVAJARJ_1 FOREIGN KEY (TIETOJARJPALVELUTUNNUS)
        REFERENCES TIETOJARJESTELMAPALVELU(TUNNUS),
    CONSTRAINT FK_TIETOJARJPALVLIITTYVAJARJ_2 FOREIGN KEY (LIITTYVAJARJESTELMATUNNUS)
        REFERENCES TIETOJARJESTELMASALKKU(TIETOJARJESTELMATUNNUS)
);

CREATE SEQUENCE TIETOJARJPALVLIITJARJ_ID_SEQ START WITH 1;

CREATE TABLE TIETOJARJPALVLIITJARJHISTORIA (
    RIVI_ID NUMBER,
    TIETOJARJPALVELUTUNNUS NUMBER,
    LIITTYVAJARJESTELMATUNNUS NUMBER,
    RIVILUOTUPVM TIMESTAMP (6),
    HISTORIATYYPPI VARCHAR2(6),
    RIVIMUOKKAAJATUNNUS VARCHAR2(150)
);

CREATE SEQUENCE TJPLIITTYVAJARJHIST_ID_SEQ START WITH 1;
