CREATE TABLE "TIETOK"."HENKILO_TEMP" (
  "TUNNUS" NUMBER NOT NULL,
  "OBJECT_ID" VARCHAR2(36 CHAR) NOT NULL,
  "NAYTTONIMI" VARCHAR2(255 CHAR),
  "TUNNUSTYYPPI" VARCHAR2(255 CHAR),
  "POISTUNUT" NUMBER(1),
  "KAYTTAJATUNNUS" VARCHAR2(255 CHAR),
  "YRITYS" VARCHAR2(255 CHAR),
  "YRITYSTUNNUS" VARCHAR2(255 CHAR),
  "ETUNIMI" VARCHAR2(255 CHAR),
  "SUKUNIMI" VARCHAR2(255 CHAR),
  "SAHKOPOSTI" VARCHAR2(255 CHAR),
  "MATKAPUHELIN" VARCHAR2(255 CHAR),
CONSTRAINT "HENKILO_TEMP_PK" PRIMARY KEY ("TUNNUS"));
