DROP TABLE SOVELLUS CASCADE;

CREATE TABLE SOVELLUS (
  "TUNNUS" NUMBER NOT NULL,
  "VALMISTAJA" VARCHAR2(255),
  "NIMI" VARCHAR2(255) NOT NULL UNIQUE,
  "ALIAS_NIMET" VARCHAR2(255),
  "VERSIO" VARCHAR2(255),
  "KONFIGURAATIO_VERSIO" VARCHAR2(255),
  "LISATIETOJA" VARCHAR2(4000),
  "SOVELLUS_TYYPPI" VARCHAR2(255),
  "KIELISYYS" VARCHAR2(255),
  "KAYTTOJARJESTELMAVAATIMUS" VARCHAR2(255),
  "ARKKITEHTUURI" VARCHAR2(255),
  "ALUSTA" VARCHAR2(255),
  "RIIPPUVUUSTIETO" VARCHAR2(255),
  "LIITTYMAT_JARJESTELMIIN" VARCHAR2(255),
  "TUOTANTOON_HYVAKSYNYT_ID" VARCHAR2(255),
  "ASENNUKSEN_HYVAKSYJA_ID" VARCHAR2(255),
  "TUOTANTOON_HYVAKSYMISPAIVA" DATE,
  "KRIITTISYYS" NUMBER,
  "ELINKAARITIETO" VARCHAR2(4000),
  "POISTUNUT" NUMBER DEFAULT 0 NOT NULL,
CONSTRAINT "SOVELLUS_POISTUNUT_CHECK" CHECK (POISTUNUT IN (0, 1)),
CONSTRAINT "SOVELLUS_PK" PRIMARY KEY ("TUNNUS"));

create sequence sovellus_seq start with 1;
create sequence sovellus_id_seq start with 1;

CREATE TABLE SOVELLUS_HISTORY (
  "RIVITUNNUS" NUMBER NOT NULL,
  "TUNNUS" NUMBER NOT NULL REFERENCES SOVELLUS,
  "ELINKAARITIETO" VARCHAR2(4000),
  "POISTUNUT" NUMBER DEFAULT 0 NOT NULL,
  "HISTORIATYYPPI" VARCHAR2(6) NOT NULL,
  "RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
CONSTRAINT "SOVELLUS_HIST_POISTUNUT_CHECK" CHECK (POISTUNUT IN (0, 1)),
CONSTRAINT "SOVELLUS_HISTORY_PK" PRIMARY KEY ("RIVITUNNUS"));

create sequence sovellus_hist_seq start with 1;
create sequence sovellus_hist_id_seq start with 1;

CREATE TABLE SOVELLUS_TEMP (
  "VALMISTAJA" VARCHAR2(255),
  "NIMI" VARCHAR2(255) NOT NULL UNIQUE,
  "ALIAS_NIMET" VARCHAR2(255),
  "VERSIO" VARCHAR2(255),
  "KONFIGURAATIO_VERSIO" VARCHAR2(255),
  "LISATIETOJA" VARCHAR2(4000),
  "SOVELLUS_TYYPPI" VARCHAR2(255),
  "KIELISYYS" VARCHAR2(255),
  "KAYTTOJARJESTELMAVAATIMUS" VARCHAR2(255),
  "ARKKITEHTUURI" VARCHAR2(255),
  "ALUSTA" VARCHAR2(255),
  "RIIPPUVUUSTIETO" VARCHAR2(255),
  "LIITTYMAT_JARJESTELMIIN" VARCHAR2(255),
  "TUOTANTOON_HYVAKSYNYT_ID" VARCHAR2(255),
  "ASENNUKSEN_HYVAKSYJA_ID" VARCHAR2(255),
  "TUOTANTOON_HYVAKSYMISPAIVA" DATE,
  "KRIITTISYYS" NUMBER);

CREATE TABLE SOVELLUS_HENKILO_ROOLI (
  "HENKILO_ID" NUMBER NOT NULL REFERENCES HENKILO,
  "ROOLI_ID" NUMBER NOT NULL REFERENCES ROOLI,
  "SOVELLUS_ID" NUMBER NOT NULL REFERENCES SOVELLUS,
  "RIVITUNNUS" NUMBER NOT NULL,
CONSTRAINT "SOVELLUS_HENKILO_ROOLI_PK" PRIMARY KEY ("HENKILO_ID", "ROOLI_ID", "SOVELLUS_ID"));

create sequence joinsovellushenkrooli_seq start with 1;
create sequence joinsovellushenkrooli_id_seq start with 1;

CREATE TABLE SOVELLUS_HENKILO_ROOLI_HIST (
  "RIVITUNNUS" NUMBER NOT NULL,
  "HENKILO_ID" NUMBER NOT NULL REFERENCES HENKILO,
  "ROOLI_ID" NUMBER NOT NULL REFERENCES ROOLI,
  "SOVELLUS_ID" NUMBER NOT NULL REFERENCES SOVELLUS,
  "HISTORIATYYPPI" VARCHAR2(6) NOT NULL,
  "RIVILUOTUPVM" TIMESTAMP (6),
  "RIVIMUOKKAAJATUNNUS" VARCHAR2(150),
CONSTRAINT "SOVELLUS_HENKILO_ROOLI_HIST" PRIMARY KEY ("RIVITUNNUS"));

create sequence sovhenkroolihist_seq start with 1;
create sequence sovhenkroolihist_id_seq start with 1;

INSERT INTO ROOLI (TUNNUS, NIMI) VALUES (4, 'TUOTANTOON_HYVAKSYNYT');
INSERT INTO ROOLI (TUNNUS, NIMI) VALUES (5, 'ASENNUKSEN_HYVAKSYNYT');

