ALTER TABLE SOVELLUS_TEMP DROP COLUMN TUOTANTOON_HYVAKSYNYT_ID;
ALTER TABLE SOVELLUS_TEMP DROP COLUMN ASENNUKSEN_HYVAKSYJA_ID;

ALTER TABLE SOVELLUS DROP COLUMN TUOTANTOON_HYVAKSYNYT_ID;
ALTER TABLE SOVELLUS DROP COLUMN ASENNUKSEN_HYVAKSYJA_ID;

ALTER TABLE SOVELLUS MODIFY KRIITTISYYS VARCHAR2(4000);
ALTER TABLE SOVELLUS_TEMP MODIFY KRIITTISYYS VARCHAR2(4000);

ALTER TABLE SOVELLUS_TEMP ADD TUOTEKOODI VARCHAR2(255);
ALTER TABLE SOVELLUS ADD TUOTEKOODI VARCHAR2(255);

ALTER TABLE SOVELLUS DROP COLUMN NIMI;
ALTER TABLE SOVELLUS_TEMP DROP COLUMN NIMI;

ALTER TABLE SOVELLUS ADD NIMI VARCHAR(255) NOT NULL;
ALTER TABLE SOVELLUS_TEMP ADD NIMI VARCHAR(255) NOT NULL;
ALTER TABLE SOVELLUS ADD CONSTRAINT SOVELLUS_UNIQUE UNIQUE (NIMI, TUOTEKOODI, VERSIO);
ALTER TABLE SOVELLUS_TEMP ADD CONSTRAINT SOVELLUS_TEMP_UNIQUE UNIQUE (NIMI, TUOTEKOODI, VERSIO);