package fi.liike.rest.api;

public enum Catalogue {
	JARJESTELMA, PALVELU, LOOGINEN, FYYSINEN, PAATIETORYHMA, TIETORYHMA, TIETOLAJI, SOVELLUS, MOLEKYYLILINKKI, HENKILO,
	TIETOARKKITEHTUURI, TIETOJARJESTELMAPALVELU, TIETOOMAISUUS, TIETOVARANTO, TOIMINTAPROSESSI,
	ORGANISAATIO, TERMILOMAKE, TERMILOMAKE_HIERARKKINEN_KASITE, TERMILOMAKE_KOOSTUMUSSUHT_KASITE,
	TERMILOMAKE_ASSOS_KASITE, TIETOSUOJAVASTAAVA
}
